spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/STUDY?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yoon2023615

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

  profiles:
    include: oauth
  devtools:
    livereload:
      enabled: true